[2025-08-20T21:05:16.877+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_pipeline.load_labeled_transactions_raw manual__2025-08-20T21:04:57.350531+00:00 [queued]>
[2025-08-20T21:05:17.042+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_pipeline.load_labeled_transactions_raw manual__2025-08-20T21:04:57.350531+00:00 [queued]>
[2025-08-20T21:05:17.043+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-20T21:05:17.064+0000] {taskinstance.py:2214} INFO - Executing <Task(AirbyteTriggerSyncOperator): load_labeled_transactions_raw> on 2025-08-20 21:04:57.350531+00:00
[2025-08-20T21:05:17.073+0000] {standard_task_runner.py:60} INFO - Started process 567 to run task
[2025-08-20T21:05:17.077+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'fraud_detection_pipeline', 'load_labeled_transactions_raw', 'manual__2025-08-20T21:04:57.350531+00:00', '--job-id', '107', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmpn9m6xv5u']
[2025-08-20T21:05:17.080+0000] {standard_task_runner.py:88} INFO - Job 107: Subtask load_labeled_transactions_raw
[2025-08-20T21:05:17.167+0000] {task_command.py:423} INFO - Running <TaskInstance: fraud_detection_pipeline.load_labeled_transactions_raw manual__2025-08-20T21:04:57.350531+00:00 [running]> on host f3fd0a28023e
[2025-08-20T21:05:17.312+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fraud_detection_pipeline' AIRFLOW_CTX_TASK_ID='load_labeled_transactions_raw' AIRFLOW_CTX_EXECUTION_DATE='2025-08-20T21:04:57.350531+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-20T21:04:57.350531+00:00'
[2025-08-20T21:05:17.349+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:05:18.062+0000] {airbyte.py:86} INFO - Job 48 was submitted to Airbyte Server
[2025-08-20T21:05:18.062+0000] {airbyte.py:88} INFO - Waiting for job 48 to complete
[2025-08-20T21:05:21.089+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:05:24.157+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:05:27.249+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:05:30.295+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:05:33.335+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:05:36.371+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:05:39.411+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:05:42.443+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:05:45.478+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:05:48.513+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:05:51.549+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:05:54.579+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:05:57.605+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:00.633+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:03.661+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:06.684+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:09.710+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:12.758+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:15.784+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:18.825+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:21.850+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:24.898+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:27.956+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:31.000+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:34.049+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:37.083+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:40.124+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:43.173+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:46.242+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:49.308+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:52.357+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:55.393+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:06:58.439+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:07:01.509+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:07:04.578+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:07:07.632+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:07:10.665+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:07:13.721+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:07:16.761+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:07:19.806+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:07:22.873+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:07:25.926+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:07:28.973+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:07:32.046+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:07:35.111+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:07:38.159+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:07:41.185+0000] {base.py:83} INFO - Using connection ID 'airbyte' for task execution.
[2025-08-20T21:07:41.205+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/airbyte/operators/airbyte.py", line 111, in execute
    hook.wait_for_job(job_id=self.job_id, wait_seconds=self.wait_seconds, timeout=self.timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/airbyte/hooks/airbyte.py", line 141, in wait_for_job
    raise Exception(f"Encountered unexpected state `{state}` for job_id `{job_id}`")
Exception: Encountered unexpected state `failed` for job_id `48`
[2025-08-20T21:07:41.217+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=fraud_detection_pipeline, task_id=load_labeled_transactions_raw, execution_date=20250820T210457, start_date=20250820T210516, end_date=20250820T210741
[2025-08-20T21:07:41.236+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 107 for task load_labeled_transactions_raw (Encountered unexpected state `failed` for job_id `48`; 567)
[2025-08-20T21:07:41.272+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-20T21:07:41.295+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
