[2025-08-20T17:43:31.735+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: fraud_detection_pipeline.load_labeled_transactions_raw manual__2025-08-20T17:42:55.831718+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
