[2025-08-20T23:15:58.990+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fraud_detection_pipeline.audit_labeled_transactions manual__2025-08-20T23:14:29.235873+00:00 [queued]>
[2025-08-20T23:15:59.125+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fraud_detection_pipeline.audit_labeled_transactions manual__2025-08-20T23:14:29.235873+00:00 [queued]>
[2025-08-20T23:15:59.126+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2025-08-20T23:15:59.137+0000] {taskinstance.py:2214} INFO - Executing <Task(BashOperator): audit_labeled_transactions> on 2025-08-20 23:14:29.235873+00:00
[2025-08-20T23:15:59.144+0000] {standard_task_runner.py:60} INFO - Started process 10525 to run task
[2025-08-20T23:15:59.147+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'fraud_detection_pipeline', 'audit_labeled_transactions', 'manual__2025-08-20T23:14:29.235873+00:00', '--job-id', '131', '--raw', '--subdir', 'DAGS_FOLDER/fraud_detection_pipeline.py', '--cfg-path', '/tmp/tmp1hs49w2w']
[2025-08-20T23:15:59.148+0000] {standard_task_runner.py:88} INFO - Job 131: Subtask audit_labeled_transactions
[2025-08-20T23:15:59.196+0000] {task_command.py:423} INFO - Running <TaskInstance: fraud_detection_pipeline.audit_labeled_transactions manual__2025-08-20T23:14:29.235873+00:00 [running]> on host f3fd0a28023e
[2025-08-20T23:15:59.275+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fraud_detection_pipeline' AIRFLOW_CTX_TASK_ID='audit_labeled_transactions' AIRFLOW_CTX_EXECUTION_DATE='2025-08-20T23:14:29.235873+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-20T23:14:29.235873+00:00'
[2025-08-20T23:15:59.277+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-08-20T23:15:59.277+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'soda scan -d staging -c include/soda/configuration.yml include/soda/checks/tables/labeled_transactions.yml']
[2025-08-20T23:15:59.291+0000] {subprocess.py:86} INFO - Output:
[2025-08-20T23:15:59.292+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: soda: command not found
[2025-08-20T23:15:59.293+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2025-08-20T23:15:59.307+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2025-08-20T23:15:59.310+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=fraud_detection_pipeline, task_id=audit_labeled_transactions, execution_date=20250820T231429, start_date=20250820T231558, end_date=20250820T231559
[2025-08-20T23:15:59.323+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 131 for task audit_labeled_transactions (Bash command failed. The command returned a non-zero exit code 127.; 10525)
[2025-08-20T23:15:59.359+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-08-20T23:15:59.381+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
